Fixed bug in design2str function.
kkmann/adoptr pull request #247
Opened 2023-03-31 12:28 UTC by nbruder

This pull request aims to solve issue #246

2023-04-03 07:20 UTC, kkmann requested changes
Hey, thanks for the PR - good spot!

Could you please stick to tidyverse style guidelines (whitespace!) for your contributed code? Otherwise looking good 👍🏻 https://style.tidyverse.org/

2023-04-03 07:20 UTC, kkmann commented on R/TwoStageDesign.R
> +    n2_piv <- seq(design@c1f,design@c1e,length.out=100)
could you expose length.out as optional argument to design2str?

2023-04-04 08:39 UTC, nbruder commented
I fixed the issues you pointed out in the new commit. Thanks for the review!

2023-04-05 10:04 UTC, kkmann approved these changes

2023-04-05 10:04 UTC, merged